language: python

python:
  - "3.4"
  - "3.5"

env:
  global:
    - GITHUB_REPO: "krischer/jane"
    - secure: "K3jhjssc4QJgDa2wmB2rtRHXdesrGb/ozkAfOeLixTpOwiS13QtAcOp2dDewJn1qWtg0iiottGQsP0hl+vdmUpHUiBa/lmawl/jLwl6yWRaZ8lC3qpOxRL/gOUtjRHYeVlAvDfbw/UAYUtMyk8N7Q2e057afQSeSgmvEe+0ADp3eYY6r4ZgKfFrqi7sitBuQO8hcdZU0T6GcP1jKE9olFiEzDwm/f4bpoO4MFiyKzcuSmI+zprq/EdUcwgqiNg2Jf87Uy8mFx5B+SXxPDhdNYv4tqG11fDqruSuHLfeSps/az4PbQF8EH9+vOXbaV9bPL1kvLWk1s2fGWUL5hKibWIvixuN40NA8123/VofEkti6WpljJRdMXm/aIE7ebzG55/FopzPflH+ZZSRoG4b7MfKBh4IvagQ8aLp+e2tb2U6LjO/rtFIITn9irq2FpFzwE1tq2wI8HGZGAtXV0P2peLvvPyPfNUjJJ45G6c/SE3NtFTrcmthDRs2G+H1jtG2MBJdHLwy+lG8x3HnZqDvBR3znQ9jmU3E7Aj4G3BO44VE+EjZLjQbNMdr7DZcq9qPoQlqHpxkpnxxC2QeiMytyZq2bGpD1dKGfTM4cZVT/U4mm2D1R65tgK3lAcVLgI/RV+F4ECNZ7NNIjVBJ1ljvai2C02ahTT0JK5uXwbaU9DFE="

services:
    - postgresql

addons:
    postgresql: "9.4"

before_script:
    - createuser --superuser test_jane

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
  - conda install --yes -c obspy obspy psycopg2 markdown flake8 gdal pyyaml pip
  - pip install codecov "django>=1.9,<1.10" djangorestframework djangorestframework-gis djangorestframework-jsonp djangorestframework-xml djangorestframework-yaml django-cors-headers django-debug-toolbar django-plugins defusedxml geojson markdown mkdocs mkdocs-bootswatch
  # Copy local_settings template.
  - cp $TRAVIS_BUILD_DIR/src/jane/local_settings.py.example $TRAVIS_BUILD_DIR/src/jane/local_settings.py

install:
  - git version
  - git fetch origin --tags --unshallow
  - git remote add jane git://github.com/krischer/jane.git
  - git fetch jane --tags
  - git status
  - git status

script:
  - cd $TRAVIS_BUILD_DIR/src; coverage run ./manage.py test

after_success:
  - mv .coverage ../.coverage.empty
  - cd ..
  - coverage combine
  - codecov
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then bash $TRAVIS_BUILD_DIR/.travis-update-gh-pages.sh ; fi
