language: python

python:
  - "3.4"
  - "3.5"

services:
    - postgresql

addons:
    postgresql: "9.4"

before_script:
    - createuser --superuser test_jane

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
  - conda install --yes -c obspy obspy psycopg2 markdown flake8 gdal pyyaml pip
  - pip install coveralls "django>=1.9,<1.10" djangorestframework djangorestframework-gis djangorestframework-jsonp djangorestframework-xml djangorestframework-yaml django-cors-headers django-debug-toolbar django-plugins defusedxml geojson markdown mkdocs mkdocs-bootswatch

install:
  - git version
  - git fetch origin --tags --unshallow
  - git remote add jane git://github.com/krischer/jane.git
  - git fetch jane --tags
  - git status
  - git status

script:
  - coverage run ./manage.py test

after_success:
  - cd $TRAVIS_BUILD_DIR; coveralls
