site_name: Jane Docs
repo_url: https://github.com/krischer/jane/
use_directory_urls: false
pages:
- 'Index': 'index.md'
- 'Setup': 'setup.md'
- 'Internals': 'internals.md'
- 'REST Interface': 'rest.md'
- 'Settings': 'settings.md'
